
include(${CMAKE_CURRENT_LIST_DIR}/../../config.cmake)

#set (WAMR_BUILD_TARGET THUMBv7em_VFP)

set (WAMR_BUILD_AOT 0) 
set (WAMR_BUILD_INTERP 1)
set (WAMR_BUILD_QUICK_AOT_ENTRY 0)
#set (WAMR_BUILD_MEMORY_PROFILING 1)